### ISSUE TITLE
Replace all SIGN occurrences with OAK_SIGN in default config

### ISSUE THREAD

**Issue by Jose-Paulo-FaD** [Multitallented/Civs#168]
Uncommenting all the region types in the default config throws errors in the console about spigot not being able to find a SIGN material. This can be easily fixed by replacing all occurrences of SIGN with OAK_SIGN.

**Comment by minus1over12** [comment]
This should have already been fixed by 860a7d8ea2cf3b026a2c78776608f6f0e2512c47

Can you double check your Civs version and make sure that the sign item group settings in your config match the [default](https://github.com/Multitallented/Civs/blob/97ad6c205cb500b9595b62c42b3af7284bebdb80/Civs/config.yml#L146).

**Comment by Jose-Paulo-FaD** [comment]
I'm using Civs 1.7.4 and the folder that comes bundled in the .zip as the config. The commit you linked fixes the signs in the groups, but the errors I was having were caused by by regions that specify the old sign material as their shop-icon. Namely, the capitol, city hall, town hall, council room and embassy.

**Comment by Multitallented** [comment]
This would be a very easy thing for someone else to fix :)

**Comment by ZombiMigz** [comment]
#170
