### ISSUE TITLE
Communism's Town Menu Has Problems

### ISSUE THREAD

**Issue by bzhaoqi** [Multitallented/Civs#214]
Pops and other cannot be displayed in player case

**Comment by Multitallented** [comment]
Once you open the town menu and click on the government type button for the first time, it will display all government types. If you click on one of these types, it will select it as your town's new government type.

Since you selected Communism, your town is now a communist type, which means that all town members are considered town owners. That's why you can't change the government type again. You do not have a single town owner who can change it. You must either have an admin change it in the files and use /cv reload, or you can revolt by having >50% of your town members click the torch in the town menu.
