### ISSUE TITLE
Can not invite new players join in my town.

### ISSUE THREAD

**Issue by nikissXI** [Multitallented/Civs#91]
Open the book-community-players-can not open other players' files, clicking on other player's head has no response.
civs1.6.5，paperspigot1.15.2
![image](https://user-images.githubusercontent.com/31379266/75833662-a92e2b00-5df4-11ea-8e07-2f03a5b20183.png)

**Comment by Multitallented** [comment]
Are you running the server in offline mode?

**Comment by Multitallented** [comment]
What government type is your town?

**Comment by nikissXI** [comment]
Yes, offline mode. 
I think that is not the government type problem. I can invite players join in my shelter when I used 1.5.X Civs. But update to 1.6.X, it doesn't work. I have try 1.6.1 to 1.6.5 (I have reset all the data and config). Can not invite new member is a big problem.

**Comment by arramcv** [comment]
Dear author：
 I'm a player of CIVS in nikissXI‘s server，I’m a builder and I have already reach the metropolis.  CIVS is great ，and I want to ask some questions:
1. “warrior、 builder、 merchant”，these three “paths” .Is that you want  to give a fixed development direction to those players who are choosing "paths".For example ,I have chose ”builder“，and am I MUST become a leader of town ? In another hand ,if I am a "warrior",I have to become a attacker and attack other players or towns？ Because the “guide” guide players to complete tasks ，and guide them to become a leader 、attacker.BUT ,some players while they chose “warrior”they just want to become a protector of a town.
IF You deliberately do so ，I think have some detailed introduce about this three paths is necessary .
Especially about what kind of feature they will face.
2.How many players in server is the best ?what‘s your opinion about the number of player ? I think CIVS is for those huge servers which have hundred or thousand players. I have notice there are two 
part in  CIVS :fight and develop .  Once  the number of players become less, they can't fight .
3.The “warehouse”，is that work like this: the production has product “stone pick”，and  transport  to "warehouse "by railway ,so the "stone pick” now in "warehouse",then stone pick transport to the mine .
NOW ,let me talk about the problem in 1.6.x .( offline mode,democratic socialism)
1.I can't open player's archives，even myself
(starter-book_player_playerA_No response）
2.As an "owner" of a town ,I can't let other players join in my town
 (starter-book_Your towns_townA_add member_palyerA_No response)
3.I can't let other player join in my building (what ever shelter、maker、factory or some else）
(starter-book_add member_palyerA_No response)
Those are the problems in 1.6.x.  But 1.5.x don't have this problem .
PLEASE repair is problem as soon as possible

**Comment by arramcv** [comment]
[1.I can't open player's archives，even myself
(starter-book_player_playerA_No response）]
PS:only the archives of Online game player can't be consult，and the archives of Offline game player can be watched.(“Online game player”means the player who has login in server， the“Offline game player”do so）

**Comment by LoJoSho** [comment]
To answer somethings in my own opinion.

1. All paths are just different ways to play. They have little to no effect on gameplay. Most of my players didn't even know which one they took. If you are unhappy with your current template, feel free to change how they work and edit the menus.

2. I can't say from @Multitallented point of view, however, I would say 20-30 players is optimal, however, you need pretty powerful hardware. 

3. Multi may have fixed this, however, I only saw that in passing.

To answer the rest of the questions:

1. We run on UUIDs, as long as your server is either ONLINE or OFFLINE but players connect through bungeecord, you should be fine. Civs doesn't support offline/cracked servers due to, as stated before, it runs on UUIDs.

2. This is all stuff that is associated with being on a cracked/offline server with no authentication. Switch to Online mode and you should be mostly good (there might still be some messed up player files just from being in offline mode). 

Multi and Louis have stated that adding support for cracked/offline servers is on the table, just at the bottom of that table.

**Comment by Multitallented** [comment]
I've fixed inviting players to towns and regions. Will be in update v1.6.6
